version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: erp-app
    restart: unless-stopped
    env_file: .env.docker
    volumes:
      - ./:/var/www
    depends_on:
      - db
    networks:
      - erpnet

  nginx:
    image: nginx:1.25-alpine
    container_name: erp-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - erpnet

  db:
    image: mysql:8.0
    container_name: erp-mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: erp
      MYSQL_USER: erp
      MYSQL_PASSWORD: erp
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - erpnet

  redis:
    image: redis:7-alpine
    container_name: erp-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - erpnet

volumes:
  dbdata:

networks:
  erpnet:
